CLASS ZCL_TEXT_STATIC DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS ITF2TEXT
    IMPORTING
      !IT_ITF TYPE TLINETAB
    RETURNING
      VALUE(RV_TEXT) TYPE STRING .
  
  CLASS-METHODS TEXT2ITF
    IMPORTING
      !IV_TEXT TYPE SIMPLE
    RETURNING
      VALUE(RT_ITF) TYPE TLINETAB .
  
  CLASS-METHODS READ
    IMPORTING
      !IV_NAME TYPE SIMPLE
      !IV_OBJECT TYPE SIMPLE DEFAULT 'TEXT'
      !IV_ID TYPE SIMPLE DEFAULT 'ST'
      !IV_LANGUAGE TYPE SIMPLE DEFAULT SY-LANGU
    RETURNING
      VALUE(RV_TEXT) TYPE STRING .
  
  CLASS-METHODS SAVE
    IMPORTING
      !IV_OBJECT TYPE SIMPLE DEFAULT 'TEXT'
      !IV_ID TYPE SIMPLE DEFAULT 'ST'
      !IV_NAME TYPE SIMPLE
      !IV_LANGUAGE TYPE SIMPLE DEFAULT SY-LANGU
      !IV_TEXT TYPE SIMPLE
      !IV_DIRECT TYPE ABAP_BOOL DEFAULT ABAP_FALSE
      !IV_COMMIT TYPE ABAP_BOOL DEFAULT ABAP_FALSE
    RAISING
      ZCX_GENERIC .
  
  CLASS-METHODS DELETE
    IMPORTING
      !IV_NAME TYPE SIMPLE
      !IV_OBJECT TYPE SIMPLE DEFAULT 'TEXT'
      !IV_ID TYPE SIMPLE DEFAULT 'ST'
      !IV_LANGUAGE TYPE SIMPLE DEFAULT SY-LANGU
      !IV_COMMIT TYPE ABAP_BOOL DEFAULT ABAP_FALSE
    RAISING
      ZCX_GENERIC .
  
  CLASS-METHODS EXISTS
    IMPORTING
      !IV_NAME TYPE SIMPLE
      !IV_OBJECT TYPE SIMPLE DEFAULT 'TEXT'
      !IV_ID TYPE SIMPLE DEFAULT 'ST'
      !IV_LANGUAGE TYPE SIMPLE DEFAULT SY-LANGU
    RETURNING
      VALUE(RV_EXISTS) TYPE ABAP_BOOL .

PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.
